### ISSUE TITLE
pin assignment & source

### ISSUE THREAD

**Issue by DjSni** [toby1984/fancontrol#1]
Hello,

I have been looking for something like this for a while. Thanks for sharing.
But unfortunately you didn't mention the pin assignment of the used Arduino. Would it be also possible to include the pure code of the Arduino (the .ino file) in the repo?

Greeting

**Comment by toby1984** [comment]
Hi,

Since I've build this project using an AVR assembler I wrote myself, I don't use .ino files.

But assuming an Arduino UNO (AVR 328p) and my comments in the source code are correct ;) the PWM output for controlling the fan speed should be D10 and the PWM output for controlling the buzzer is on D3.

HTH
